highlighter: pygments
safe: true
lsi: false

# Site settings
title: Nikos Daniilidis
description: > # this means to ignore newlines until "baseurl:"
  A blog about science, technology, society, and everything in-between.

baseurl: # "/blog"
url: "http://nikosd.me"# "http://nikos-daniilidis.github.io"

email: nikos.daniilidis@gmail.com
twitter_username: ndaniilidis
github_username:  nikos-daniilidis
linked_in: https://www.linkedin.com/in/ndaniilidis

# Build settings
markdown: kramdown

exclude: ['CNAME', 'README.md']
